version: "3.8"

services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    entrypoint: /tmp/run_ollama.sh
    volumes:
      - ollama-data:/root/.ollama
    pull_policy: always
    tty: true
    restart: always

  agent:
    build: ./agent
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama-data:
